export const rocketData = [
    {
      "id": 1,
        "image": "images/falcon_heavy.jpg",
        "information": "The Falcon Heavy, developed by SpaceX, is recognized for being the most powerful operational rocket in the world, designed to carry large payloads to orbit and support missions to Mars.", 
      "name": "Falcon Heavy",
      "group_letter": "A",
      "number": 1,
      "group": "Launchers",
      "year_built": 2018,
      "weight": 1420788,
      "max_earth_distance": 35786,
      "max_speed": 35400,
      "development_cost": 500,
      "mission_duration": 1,
      "payload": 63800,
      "involved_nations": 1,
      "mission_goal": "Heavy-lift launch vehicle",
      "lead_organization": "SpaceX",
        "": "Falcon Heavy"
      
    },
    {
      "id": 2,
        "image": "images/Saturn_V.jpg",
        "information": "Saturn V, designed by NASA for the Apollo and Skylab programs, remains the tallest, heaviest, and most powerful rocket ever brought to operational status and was crucial in enabling human exploration of the Moon.", 
      "name": "Saturn V",
      "group_letter": "A",
      "number": 2,
      "group": "Launchers",
      "year_built": 1967,
      "weight": 2970000,
      "max_earth_distance": 384400,
      "max_speed": 38400,
      "development_cost": 6500,
      "mission_duration": 1,
      "payload": 118000,
      "involved_nations": 1,
      "mission_goal": "Manned moon landing",
      "lead_organization": "NASA",
      "": "Saturn V"
    },
    {
      "id": 3,
      "image": "images/Ariane_5.jpg",
      "name": "Ariane 5",
      "group_letter": "A",
      "number": 3,
      "group": "Launchers",
      "year_built": 1996,
      "weight": 780000,
      "max_earth_distance": 35786,
      "max_speed": 11300,
      "development_cost": 7000,
      "mission_duration": 1,
      "payload": 21000,
      "involved_nations": 12,
      "mission_goal": "Heavy-lift launch vehicle",
        "lead_organization": "ESA",
        "information": "Ariane 5 is a heavy-lift launch vehicle used by the European Space Agency (ESA) for transporting payloads to geostationary transfer orbits (GTOs) and low Earth orbit (LEO), with a notable track record for reliability.", 
      "": "Ariane 5"
    },
    {
      "id": 4,
      "image": "images/Long-March.jpg",
      "name": "Long March 5",
      "group_letter": "A",
      "number": 4,
      "group": "Launchers",
      "year_built": 2016,
      "weight": 869000,
      "max_earth_distance": 35786,
      "max_speed": 10800,
      "development_cost": 8500,
      "mission_duration": 1,
      "payload": 25000,
      "involved_nations": 1,
      "mission_goal": "Heavy-lift launch vehicle",
        "lead_organization": "CNSA",
        "information": "Long March 5, part of China's heavy-lift rocket family, is designed for launching lunar probes and the core modules of the Chinese space station, highlighting China's growing capabilities in space.", 
      "": "Long March 5"
    },
    {
      "id": 5,
      "image": "images/electron.jpg",
      "name": "Electron",
      "group_letter": "B",
      "number": 1,
      "group": "Light rockets",
      "year_built": 2017,
      "weight": 12080,
      "max_earth_distance": 2000,
      "max_speed": 27500,
      "development_cost": 90,
      "mission_duration": 1,
      "payload": 300,
      "involved_nations": 1,
      "mission_goal": "Small satellite launch",
        "lead_organization": "Rocket Lab",
        "information": "The Electron rocket, developed by Rocket Lab, is a lightweight, cost-effective vehicle designed for launching small satellites into low Earth orbits, making space more accessible to commercial customers.", 
      "": "Electron"
    },
    {
      "id": 6,
      "image": "images/vega.jpg",
      "name": "Vega",
      "group_letter": "B",
      "number": 2,
      "group": "Light rockets",
      "year_built": 2012,
      "weight": 137000,
      "max_earth_distance": 700,
      "max_speed": 28750,
      "development_cost": 1200,
      "mission_duration": 1,
      "payload": 1500,
      "involved_nations": 10,
      "mission_goal": "Small satellite launch",
        "lead_organization": "ESA",
        "information": "Vega, developed by ESA, is an expendable launch system used to deliver small payloads, such as satellites, into polar and low Earth orbits, designed to accommodate a wide range of missions.", 
      "": "Vega"
    },
    {
      "id": 7,
      "image": "images/falcon01.jpg",
      "name": "Falcon 1",
      "group_letter": "B",
      "number": 3,
      "group": "Light rockets",
      "year_built": 2006,
      "weight": 38556,
      "max_earth_distance": 2000,
      "max_speed": 27500,
      "development_cost": 90,
      "mission_duration": 1,
      "payload": 670,
      "involved_nations": 1,
      "mission_goal": "Technology demonstration",
        "lead_organization": "SpaceX",
        "information": "Falcon 1 was SpaceX's first orbital rocket, marking the first privately developed liquid-fueled rocket to reach orbit, serving as a stepping stone for the development of more advanced Falcon rockets.", 
      "": "Falcon 1"
    },
    {
      "id": 8,
      "image": "images/pegasus.jpg",
      "name": "Pegasus",
      "group_letter": "B",
      "number": 4,
      "group": "Light rockets",
      "year_built": 1990,
      "weight": 18500,
      "max_earth_distance": 2000,
      "max_speed": 28000,
      "development_cost": 1400,
      "mission_duration": 1,
      "payload": 443,
      "involved_nations": 1,
      "mission_goal": "Small satellite launch",
        "lead_organization": "Northrop Grumman",
        "information": "Pegasus is an air-launched rocket system developed by Northrop Grumman, capable of launching small satellites into space from an aircraft instead of from the ground, offering flexibility in launch locations.", 
      "": "Pegasus"
    },
    {
        "id": 9,
        "image": "images/voyager.jpg",
      "name": "Voyager 1",
      "group_letter": "C",
      "number": 1,
      "group": "Probes",
      "year_built": 1977,
      "weight": 773,
      "max_earth_distance": 22286000,
      "max_speed": 62000,
      "development_cost": 250,
      "mission_duration": 19000,
      "payload": 0,
      "involved_nations": 1,
        "mission_goal": "Solar system exploration",
        "information": "Voyager 1, a deep space probe launched by NASA in 1977, has entered interstellar space, making it one of the furthest man-made objects from Earth and providing valuable data about the outer planets and beyond.", 
      "lead_organization": "NASA",
      "": "Voyager 1"
    },
    {
      "id": 10,
      "image": "images/dart.jpg",
      "name": "DART",
      "group_letter": "C",
      "number": 2,
      "group": "Probes",
      "year_built": 2021,
      "weight": 610,
      "max_earth_distance": 11000000,
      "max_speed": 24140,
      "development_cost": 330,
      "mission_duration": 301,
      "payload": 0,
        "involved_nations": 1,
        "information": "DART (Double Asteroid Redirection Test) is NASA's mission aimed at testing technologies for preventing an impact of Earth by asteroids, by intentionally colliding with a small asteroid to alter its orbit.", 
      "mission_goal": "Planetary defense demonstration",
      "lead_organization": "NASA",
      "": "DART"
    },
    {
      "id": 11,
        "name": "New Horizons",
        "image": "images/new-horizonz.jpg",
      "group_letter": "C",
      "number": 3,
      "group": "Probes",
      "year_built": 2006,
      "weight": 478,
      "max_earth_distance": 7500000,
      "max_speed": 84000,
      "development_cost": 700,
        "mission_duration": 6000,
        "information": "New Horizons is a NASA spacecraft that provided humanity's first close-up images of Pluto and its moons, continuing to explore the Kuiper Belt and expanding our knowledge of the outer solar system.", 
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Pluto system and Kuiper belt exploration",
      "lead_organization": "NASA",
      "": "New Horizons"
    },
    {
      "id": 12,
      "image": "images/juno.jpg",
      "name": "Juno",
      "group_letter": "C",
      "number": 4,
      "group": "Probes",
      "year_built": 2011,
      "weight": 3625,
      "max_earth_distance": 928000,
      "max_speed": 265000,
      "development_cost": 1200,
      "mission_duration": 3000,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Jupiter exploration",
        "lead_organization": "NASA",
        "information": "Juno, a NASA mission, is orbiting Jupiter to understand the planet's origins, structure, atmosphere, and magnetosphere, revealing the complex nature of the largest planet in our solar system.", 
      "": "Juno"
    },
    {
      "id": 13,
      "image": "images/Hubble-Space-Telescope.jpg",
      "name": "Hubble Space Telescope",
      "group_letter": "D",
      "number": 1,
      "group": "Satellites",
      "year_built": 1990,
      "weight": 11110,
      "max_earth_distance": 559,
      "max_speed": 28000,
      "development_cost": 4600,
      "mission_duration": 10000,
      "payload": 0,
      "involved_nations": 2,
      "mission_goal": "Space observatory",
        "lead_organization": "NASA/ESA",
        "information": "The Hubble Space Telescope, a project of international cooperation between NASA and ESA, has revolutionized astronomy by providing unprecedented deep views of the universe, from solar system objects to distant galaxies.", 
      "": "Hubble Space Telescope"
    },
    {
      "id": 14,
      "image": "images/JWST.jpg",
      "name": "JWST",
      "group_letter": "D",
      "number": 2,
      "group": "Satellites",
      "year_built": 2021,
      "weight": 6200,
      "max_earth_distance": 1500000,
      "max_speed": 1500000,
      "development_cost": 10000,
      "mission_duration": 5475,
      "payload": 0,
      "involved_nations": 15,
      "mission_goal": "Space observatory",
        "lead_organization": "NASA/ESA/CSA",
        "information": "The James Webb Space Telescope (JWST), launched in 2021, represents a significant advancement in space telescopes, designed to study the universe's history, from the Big Bang to the formation of solar systems capable of supporting life on planets like Earth.", 
      "": "JWST"
    },
    {
      "id": 15,
      "image": "images/kepler.jpg",
      "name": "Kepler",
      "group_letter": "D",
      "number": 3,
      "group": "Satellites",
      "year_built": 2009,
      "weight": 1032,
      "max_earth_distance": 149600000,
      "max_speed": 107000,
      "development_cost": 550,
      "mission_duration": 1470,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Exoplanet discovery",
        "lead_organization": "NASA",
        "information": "Kepler is a space observatory launched by NASA to discover Earth-size planets orbiting other stars, notably contributing to the field of exoplanet research with thousands of discovered exoplanets.", 
      "": "Kepler"
    },
    {
      "id": 16,
      "image": "images/GPS-Block-IIIA.jpg",
      "name": "GPS Block IIIA",
      "group_letter": "D",
      "number": 4,
      "group": "Satellites",
      "year_built": 2018,
      "weight": 3680,
      "max_earth_distance": 20200,
      "max_speed": 14000,
      "development_cost": 577,
      "mission_duration": 5475,
        "payload": 0,
        "information": "GPS Block IIIA satellites, part of the next generation of GPS satellites deployed by the US Air Force, offer improved accuracy, enhanced security, and better resistance to interference for all users around the globe.", 
      "involved_nations": 1,
      "mission_goal": "Navigation",
      "lead_organization": "US Air Force",
      "": "GPS Block IIIA"
    },
    {
      "id": 17,
      "image": "images/Curiosity.jpg",
      "name": "Curiosity",
      "group_letter": "E",
      "number": 1,
      "group": "Rovers",
      "year_built": 2011,
      "weight": 899,
      "max_earth_distance": 225000000,
      "max_speed": 0.14,
      "development_cost": 2500,
      "mission_duration": 3000,
      "payload": 0,
        "involved_nations": 1,
        "information": "Curiosity, NASA's Mars rover, is equipped with instruments to analyze rocks, soils, and the atmosphere on Mars, contributing significantly to our understanding of the planet's habitability.", 
      "mission_goal": "Mars exploration",
      "lead_organization": "NASA",
      "": "Curiosity"
    },
    {
      "id": 18,
      "image": "images/Perseverance.jpg",
      "name": "Perseverance",
      "group_letter": "E",
      "number": 2,
      "group": "Rovers",
      "year_built": 2020,
      "weight": 1025,
      "max_earth_distance": 225000000,
      "max_speed": 0.16,
      "development_cost": 2700,
      "mission_duration": 700,
      "payload": 0,
        "involved_nations": 1,
        "information": "Perseverance, part of NASA's Mars 2020 mission, is exploring the Red Planet's surface with technology aimed at finding signs of past microbial life and collecting samples for future return to Earth.", 
      "mission_goal": "Mars exploration",
      "lead_organization": "NASA",
      "": "Perseverance"
    },
    {
      "id": 19,
      "image": "images/Zhurong.jpg",
      "name": "Zhurong",
      "group_letter": "E",
      "number": 3,
      "group": "Rovers",
      "year_built": 2021,
      "weight": 240,
      "max_earth_distance": 225000000,
      "max_speed": 0.2,
      "development_cost": 300,
      "mission_duration": 100,
      "payload": 0,
      "involved_nations": 1,
        "mission_goal": "Mars exploration",
        "information": "Zhurong, launched by China's CNSA, is the first Chinese Mars rover, exploring the Martian surface to study the planet's soil, structure, atmosphere, and search for signs of water.", 
      "lead_organization": "CNSA",
      "": "Zhurong"
    },
    {
      "id": 20,
      "image": "images/Opportunity.jpg",
      "name": "Opportunity",
      "group_letter": "E",
      "number": 4,
      "group": "Rovers",
      "year_built": 2003,
      "weight": 185,
      "max_earth_distance": 225000000,
        "max_speed": 0.18,
        "information": "Opportunity, a Mars rover mission operated by NASA, significantly exceeded its expected lifespan and operational goals, providing valuable data on the Martian environment and geology.", 
      "development_cost": 400,
      "mission_duration": 5111,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Mars exploration",
      "lead_organization": "NASA",
      "": "Opportunity"
    },
    {
      "id": 21,
      "image": "images/falcon_heavy.jpg",
      "name": "InSight",
      "group_letter": "F",
      "number": 1,
      "group": "Landers",
      "year_built": 2018,
      "weight": 694,
      "max_earth_distance": 225000000,
      "max_speed": 0,
      "development_cost": 830,
      "mission_duration": 709,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Mars exploration",
        "lead_organization": "NASA",
        "information": "InSight, a NASA Mars lander, is designed to study the deep interior of Mars, aiming to provide insights into the processes that shaped the rocky planets of the solar system.", 
      "": "InSight"
    },
    {
      "id": 22,
      "image": "images/Change-4.jpg",
      "name": "Chang'e 4",
      "group_letter": "F",
      "number": 2,
      "group": "Landers",
      "year_built": 2019,
      "weight": 3780,
      "max_earth_distance": 384400,
      "max_speed": 0,
      "development_cost": 180,
      "mission_duration": 1000,
      "payload": 0,
      "involved_nations": 1,
        "mission_goal": "Moon exploration",
        "information": "Chang'e 4, launched by CNSA, is the first spacecraft to land on the far side of the Moon, exploring its surface and providing key data to expand our understanding of Earth's satellite.", 
      "lead_organization": "CNSA",
      "": "Chang'e 4"
    },
    {
      "id": 23,
      "image": "images/Venera10.jpg",
      "name": "Venera 10",
      "group_letter": "F",
      "number": 3,
      "group": "Landers",
      "year_built": 1975,
      "weight": 5030,
      "max_earth_distance": 40000000,
      "max_speed": 0,
      "development_cost": 60,
      "mission_duration": 1,
      "payload": 0,
      "involved_nations": 1,
        "mission_goal": "Venus exploration",
        "information": "Venera 10, a mission by the Soviet Union, successfully landed on Venus and transmitted the first images from the Venusian surface, revealing insights about its atmosphere and geology." ,
      "lead_organization": "Soviet Union",
      "": "Venera 10"
    },
    {
      "id": 24,
      "image": "images/Hayabusa2.jpg",
      "name": "Hayabusa2",
      "group_letter": "F",
      "number": 4,
      "group": "Landers",
      "year_built": 2014,
      "weight": 609,
      "max_earth_distance": 340000000,
      "max_speed": 0,
      "development_cost": 150,
      "mission_duration": 2190,
      "payload": 0,
        "involved_nations": 1,
        "information": "Hayabusa2, a JAXA mission, is designed to visit an asteroid to collect samples and return them to Earth for analysis, contributing to our knowledge of the early solar system."
, 
      "mission_goal": "Asteroid sample return",
      "lead_organization": "JAXA",
      "": "Hayabusa2"
    },
    {
      "id": 25,
        "image": "images/ISS.jpg",
        "information": "The International Space Station (ISS), a joint project among five space agencies, serves as a microgravity and space environment research laboratory, hosting astronauts from around the world.", 
      "name": "ISS",
      "group_letter": "G",
      "number": 1,
      "group": "Space Stations",
      "year_built": 1998,
      "weight": 419725,
      "max_earth_distance": 408,
      "max_speed": 28000,
      "development_cost": 150000,
      "mission_duration": 9000,
      "payload": 0,
      "involved_nations": 15,
      "mission_goal": "Space research laboratory",
      "lead_organization": "International partnership",
      "": "ISS"
    },
    {
      "id": 26,
      "image": "images/Tiangong.jpg",
        "name": "Tiangong",
        "information": "Tiangong, China's space station, represents a significant step in China's human spaceflight capabilities, serving as a laboratory for science and technology experiments in low Earth orbit.", 
      "group_letter": "G",
      "number": 2,
      "group": "Space Stations",
      "year_built": 2021,
      "weight": 66000,
      "max_earth_distance": 400,
      "max_speed": 28000,
      "development_cost": 2000,
      "mission_duration": 5475,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Space research laboratory",
      "lead_organization": "CNSA",
      "": "Tiangong"
    },
    {
      "id": 27,
        "image": "images/Mir.jpg",
        "information": "Mir was a space station operated by the Soviet Union and later by Russia, known for being the first continuously inhabited long-term research station in orbit and playing a key role in human spaceflight history.", 
      "name": "Mir",
      "group_letter": "G",
      "number": 3,
      "group": "Space Stations",
      "year_built": 1986,
      "weight": 129700,
      "max_earth_distance": 354,
      "max_speed": 28000,
      "development_cost": 4200,
      "mission_duration": 5510,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Space research laboratory",
      "lead_organization": "Soviet Union",
      "": "Mir"
    },
    {
      "id": 28,
        "image": "images/Skylab.jpg",
        "information": "Skylab, America's first space station, was utilized for various scientific experiments concerning the effects of prolonged spaceflight on the human body and solar observations.", 
      "name": "Skylab",
      "group_letter": "G",
      "number": 4,
      "group": "Space Stations",
      "year_built": 1973,
      "weight": 77000,
      "max_earth_distance": 435,
      "max_speed": 28000,
      "development_cost": 2200,
      "mission_duration": 171,
      "payload": 0,
      "involved_nations": 1,
      "mission_goal": "Space research laboratory",
      "lead_organization": "NASA",
      "": "Skylab"
    },
    {
      "id": 29,
        "image": "images/crew-dragon.jpg",
        "information": "Crew Dragon, developed by SpaceX, has revolutionized commercial spaceflight, providing a modern transportation option to and from the International Space Station for crew members.", 
      "name": "Crew Dragon",
      "group_letter": "H",
      "number": 1,
      "group": "Manned Spacecraft",
      "year_built": 2020,
      "weight": 12200,
      "max_earth_distance": 408,
      "max_speed": 28000,
      "development_cost": 2700,
      "mission_duration": 180,
      "payload": 6000,
      "involved_nations": 1,
      "mission_goal": "Crew transport to ISS",
      "lead_organization": "SpaceX",
      "": "Crew Dragon"
    },
    {
      "id": 30,
      "image": "images/apollo-command-module.jpg",
      "name": "Apollo Command Module",
      "group_letter": "H",
      "number": 2,
      "group": "Manned Spacecraft",
      "year_built": 1966,
      "weight": 5560,
      "max_earth_distance": 400171,
      "max_speed": 39060,
      "development_cost": 25000,
      "mission_duration": 10,
      "payload": 1180,
      "involved_nations": 1,
      "mission_goal": "Manned moon landing",
      "lead_organization": "NASA",
        "": "Apollo Command Module", 
        "information": "The Apollo Command Module was part of the Apollo spacecraft used by NASA for the Apollo program which landed the first humans on the Moon.",     },
    {
      "id": 31,
      "image": "images/spaceshuttle.png",
      "name": "Space Shuttle",
      "group_letter": "H",
      "number": 3,
      "group": "Manned Spacecraft",
      "year_built": 1981,
      "weight": 78000,
      "max_earth_distance": 960,
      "max_speed": 28000,
      "development_cost": 45000,
      "mission_duration": 17,
      "payload": 24448,
        "involved_nations": 1,
        "information": "The Space Shuttle, developed by NASA, served as a partially reusable low Earth orbital spacecraft system, supporting numerous missions including satellite launch, space station resupply, and Hubble Space Telescope deployment.", 
      "mission_goal": "Various, including space research and satellite deployment",
      "lead_organization": "NASA",
      "": "Space Shuttle"
    },
    {
      "id": 32,
      "image": "images/Soyuz.jpg",
      "name": "Soyuz",
      "group_letter": "H",
      "number": 4,
      "group": "Manned Spacecraft",
      "year_built": 1966,
      "weight": 6800,
      "max_earth_distance": 408,
      "max_speed": 28000,
        "development_cost": 450,
        "information": "Soyuz spacecraft, developed by Roscosmos, have been instrumental in transporting astronauts and cosmonauts to the International Space Station, boasting an impressive track record for safety and reliability.", 
      "mission_duration": 210,
      "payload": 680,
      "involved_nations": 1,
      "mission_goal": "Crew transport to ISS",
      "lead_organization": "Roscosmos",
      "": "Soyuz"
    }
  ]