import type { Metadata } from 'next'
import { Inter, Manrope, Orbitron } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import { RocketDataContextProvider } from '@/lib/RocketDataContext'

const manrope = Manrope({ subsets: ['latin'], variable: '--manrope' })
const orbitron = Orbitron({ subsets: ['latin'], variable: '--orbitron' })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${manrope.className} ${orbitron.variable}`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    <RocketDataContextProvider>
                        <main>{children}</main>
                    </RocketDataContextProvider>
                </ThemeProvider>
            </body>
        </html>
    )
}
